### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by Marc78330** [Xgamer911/cotps_script#1]
Hello . 

thank you for your incredible job. 

I have an issue with the script. 
I 'm french so i need to change the phone extension to +33 at the login page, how can i do that ?

**Comment by Xgamer911** [comment]
I will add that as a feature for you and Ill post here when it is done.

**Comment by Xgamer911** [comment]
I have just done a release version 1.1. Version 1.1 will now ask for phone extension within the config.cfg file. In your case, simply put 33 where the 1 is and it should work. Since I don't have a number to test this against, I will leave this issue open for now, until you or someone else can test it and let me know it worked.

Also if you want to change your timezones, you can get a list here: https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568

**Comment by Marc78330** [comment]
it work like a charm, thank you so much

**Comment by Xgamer911** [comment]
Awesome, closing issue.
